CREATE TYPE "public"."payment_frequency" AS ENUM('monthly', 'quarterly', 'semi_annual', 'annual');--> statement-breakpoint
CREATE TYPE "public"."valuation_status" AS ENUM('undervalued', 'reasonably_valued', 'overvalued', 'speculative');--> statement-breakpoint
CREATE TABLE "stocks" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stocks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"symbol" text NOT NULL,
	"short_name" text,
	"long_name" text,
	"sector_id" integer,
	"country_id" integer,
	"exchange" text,
	"full_time_employees" integer,
	"market_cap" bigint,
	"dividend_rate" real,
	"dividend_yield" real,
	"ex_dividend_date" bigint,
	"dividend_date" bigint,
	"payout_ratio" real,
	"five_year_avg_dividend_yield" real,
	"trailing_annual_dividend_rate" real,
	"trailing_annual_dividend_yield" real,
	"dividend_growth_1_year" real,
	"dividend_growth_5_year" real,
	"dividend_growth_10_year" real,
	"dividend_growth_streak" integer,
	"uninterrupted_dividend_streak" integer,
	"latest_dividend_raise_date" bigint,
	"payment_frequency" "payment_frequency",
	"payment_schedule_months" text,
	"yield_relative_to_history" real,
	"recession_dividend_performance" text,
	"recession_return" real,
	"trailing_pe" real,
	"forward_pe" real,
	"price_to_book" real,
	"price_to_sales_trailing" real,
	"pe_relative_to_history" real,
	"valuation_status" "valuation_status",
	"current_price" real,
	"previous_close" real,
	"fifty_two_week_high" real,
	"fifty_two_week_low" real,
	"fifty_day_average" real,
	"two_hundred_day_average" real,
	"beta" real,
	"trailing_eps" real,
	"forward_eps" real,
	"earnings_quarterly_growth" real,
	"earnings_growth" real,
	"earnings_timestamp" bigint,
	"profit_margins" real,
	"gross_margins" real,
	"operating_margins" real,
	"free_cashflow" bigint,
	"operating_cashflow" bigint,
	"return_on_assets" real,
	"return_on_equity" real,
	"return_on_invested_capital" real,
	"debt_to_equity" real,
	"current_ratio" real,
	"quick_ratio" real,
	"net_debt_to_capital" real,
	"net_debt_to_ebitda" real,
	"credit_rating" text,
	"recommendation_key" text,
	"recommendation_mean" real,
	"target_mean_price" real,
	"target_median_price" real,
	"number_of_analyst_opinions" integer,
	"last_updated" timestamp DEFAULT now(),
	CONSTRAINT "stocks_symbol_unique" UNIQUE("symbol")
);
--> statement-breakpoint
ALTER TABLE "user" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "user" CASCADE;--> statement-breakpoint
ALTER TABLE "stocks" ADD CONSTRAINT "stocks_sector_id_sectors_id_fk" FOREIGN KEY ("sector_id") REFERENCES "public"."sectors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stocks" ADD CONSTRAINT "stocks_country_id_countries_id_fk" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "countries" ADD CONSTRAINT "countries_name_unique" UNIQUE("name");--> statement-breakpoint
ALTER TABLE "sectors" ADD CONSTRAINT "sectors_name_unique" UNIQUE("name");